[package]
name = "map_iced"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.13.4"
fxhash = "0.2.1"
tokio = { version = "1.53.1" , features = ["fs", "macros"]}
itertools = "0.15.0"
iced = {  version = "0.14.0", features = ["tokio","image", "advanced", "canvas"] }
bytes = "1.12.1"
dirs = "6.0.0"
tokio-stream = "0.1.19"

[dev-dependencies]
tempfile = "3.27.0"
proptest = "1.11.0"

